/*
 * StarkExpress API Docs
 *
 * An API for the StarkExpress platform.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using StarkExpress.SDK.Client.Client;
using StarkExpress.SDK.Client.Api;
// uncomment below to import models
//using StarkExpress.SDK.Client.Model;

namespace StarkExpress.SDK.Client.Test.Api
{
    /// <summary>
    ///  Class for testing OrderApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class OrderApiTests : IDisposable
    {
        private OrderApi instance;

        public OrderApiTests()
        {
            instance = new OrderApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' OrderApi
            //Assert.IsType<OrderApi>(instance);
        }

        /// <summary>
        /// Test CancelOrder
        /// </summary>
        [Fact]
        public void CancelOrderTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid orderId = null;
            //var response = instance.CancelOrder(orderId);
            //Assert.IsType<OrderDto>(response);
        }

        /// <summary>
        /// Test OrderDetails
        /// </summary>
        [Fact]
        public void OrderDetailsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //OrderDetailsModel orderDetailsModel = null;
            //var response = instance.OrderDetails(orderDetailsModel);
            //Assert.IsType<OrderDetailsDto>(response);
        }

        /// <summary>
        /// Test SubmitOrder
        /// </summary>
        [Fact]
        public void SubmitOrderTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //SubmitOrderModel submitOrderModel = null;
            //var response = instance.SubmitOrder(submitOrderModel);
            //Assert.IsType<OrderDto>(response);
        }
    }
}
