/*
 * StarkExpress API Docs
 *
 * An API for the StarkExpress platform.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using StarkExpress.SDK.Client.Client;
using StarkExpress.SDK.Client.Api;
// uncomment below to import models
//using StarkExpress.SDK.Client.Model;

namespace StarkExpress.SDK.Client.Test.Api
{
    /// <summary>
    ///  Class for testing TransferApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class TransferApiTests : IDisposable
    {
        private TransferApi instance;

        public TransferApiTests()
        {
            instance = new TransferApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TransferApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' TransferApi
            //Assert.IsType<TransferApi>(instance);
        }

        /// <summary>
        /// Test Transfer
        /// </summary>
        [Fact]
        public void TransferTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //TransferModel transferModel = null;
            //var response = instance.Transfer(transferModel);
            //Assert.IsType<List<VaultDto>>(response);
        }

        /// <summary>
        /// Test TransferDetails
        /// </summary>
        [Fact]
        public void TransferDetailsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //TransferDetailsModel transferDetailsModel = null;
            //var response = instance.TransferDetails(transferDetailsModel);
            //Assert.IsType<TransferDetailsDto>(response);
        }
    }
}
