/*
 * Arc API Docs
 *
 * An API for the Arc platform.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using Xunit;

using StarkExpress.SDK.Client.Client;
using StarkExpress.SDK.Client.Api;
// uncomment below to import models
//using StarkExpress.SDK.Client.Model;

namespace StarkExpress.SDK.Client.Test.Api
{
    /// <summary>
    ///  Class for testing VaultApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class VaultApiTests : IDisposable
    {
        private VaultApi instance;

        public VaultApiTests()
        {
            instance = new VaultApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of VaultApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' VaultApi
            //Assert.IsType<VaultApi>(instance);
        }

        /// <summary>
        /// Test AllocateVault
        /// </summary>
        [Fact]
        public void AllocateVaultTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //AllocateVaultModel allocateVaultModel = null;
            //var response = instance.AllocateVault(allocateVaultModel);
            //Assert.IsType<VaultDto>(response);
        }

        /// <summary>
        /// Test GetAllVaults
        /// </summary>
        [Fact]
        public void GetAllVaultsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid? assetId = null;
            //int? pageNumber = null;
            //int? pageSize = null;
            //string sortBy = null;
            //var response = instance.GetAllVaults(assetId, pageNumber, pageSize, sortBy);
            //Assert.IsType<VaultDtoPaginatedResponseDto>(response);
        }

        /// <summary>
        /// Test GetVault
        /// </summary>
        [Fact]
        public void GetVaultTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //Guid vaultId = null;
            //var response = instance.GetVault(vaultId);
            //Assert.IsType<VaultDto>(response);
        }
    }
}
