/*
 * StarkExpress API Docs
 *
 * An API for the StarkExpress platform.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using StarkExpress.SDK.Client.Api;
using StarkExpress.SDK.Client.Model;
using StarkExpress.SDK.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace StarkExpress.SDK.Client.Test.Model
{
    /// <summary>
    ///  Class for testing AllocateVaultModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AllocateVaultModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AllocateVaultModel
        //private AllocateVaultModel instance;

        public AllocateVaultModelTests()
        {
            // TODO uncomment below to create an instance of AllocateVaultModel
            //instance = new AllocateVaultModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AllocateVaultModel
        /// </summary>
        [Fact]
        public void AllocateVaultModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" AllocateVaultModel
            //Assert.IsType<AllocateVaultModel>(instance);
        }


        /// <summary>
        /// Test the property 'AssetId'
        /// </summary>
        [Fact]
        public void AssetIdTest()
        {
            // TODO unit test for the property 'AssetId'
        }
        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }
        /// <summary>
        /// Test the property 'DataAvailabilityMode'
        /// </summary>
        [Fact]
        public void DataAvailabilityModeTest()
        {
            // TODO unit test for the property 'DataAvailabilityMode'
        }
        /// <summary>
        /// Test the property 'TokenId'
        /// </summary>
        [Fact]
        public void TokenIdTest()
        {
            // TODO unit test for the property 'TokenId'
        }
        /// <summary>
        /// Test the property 'MintingBlob'
        /// </summary>
        [Fact]
        public void MintingBlobTest()
        {
            // TODO unit test for the property 'MintingBlob'
        }

    }

}
