/*
 * Arc API Docs
 *
 * An API for the Arc platform.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using StarkExpress.SDK.Client.Api;
using StarkExpress.SDK.Client.Model;
using StarkExpress.SDK.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace StarkExpress.SDK.Client.Test.Model
{
    /// <summary>
    ///  Class for testing BuyOrderDetailsModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class BuyOrderDetailsModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for BuyOrderDetailsModel
        //private BuyOrderDetailsModel instance;

        public BuyOrderDetailsModelTests()
        {
            // TODO uncomment below to create an instance of BuyOrderDetailsModel
            //instance = new BuyOrderDetailsModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BuyOrderDetailsModel
        /// </summary>
        [Fact]
        public void BuyOrderDetailsModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" BuyOrderDetailsModel
            //Assert.IsType<BuyOrderDetailsModel>(instance);
        }


        /// <summary>
        /// Test the property 'BuyerId'
        /// </summary>
        [Fact]
        public void BuyerIdTest()
        {
            // TODO unit test for the property 'BuyerId'
        }
        /// <summary>
        /// Test the property 'OfferId'
        /// </summary>
        [Fact]
        public void OfferIdTest()
        {
            // TODO unit test for the property 'OfferId'
        }
        /// <summary>
        /// Test the property 'DataAvailabilityMode'
        /// </summary>
        [Fact]
        public void DataAvailabilityModeTest()
        {
            // TODO unit test for the property 'DataAvailabilityMode'
        }

    }

}
