/*
 * Arc API Docs
 *
 * An API for the Arc platform.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using StarkExpress.SDK.Client.Api;
using StarkExpress.SDK.Client.Model;
using StarkExpress.SDK.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace StarkExpress.SDK.Client.Test.Model
{
    /// <summary>
    ///  Class for testing ConfigureFeeModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ConfigureFeeModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ConfigureFeeModel
        //private ConfigureFeeModel instance;

        public ConfigureFeeModelTests()
        {
            // TODO uncomment below to create an instance of ConfigureFeeModel
            //instance = new ConfigureFeeModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ConfigureFeeModel
        /// </summary>
        [Fact]
        public void ConfigureFeeModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" ConfigureFeeModel
            //Assert.IsType<ConfigureFeeModel>(instance);
        }


        /// <summary>
        /// Test the property 'FeeAction'
        /// </summary>
        [Fact]
        public void FeeActionTest()
        {
            // TODO unit test for the property 'FeeAction'
        }
        /// <summary>
        /// Test the property 'BasisPoints'
        /// </summary>
        [Fact]
        public void BasisPointsTest()
        {
            // TODO unit test for the property 'BasisPoints'
        }

    }

}
