/*
 * StarkExpress API Docs
 *
 * An API for the StarkExpress platform.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using StarkExpress.SDK.Client.Api;
using StarkExpress.SDK.Client.Model;
using StarkExpress.SDK.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace StarkExpress.SDK.Client.Test.Model
{
    /// <summary>
    ///  Class for testing CreateOrderbookModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateOrderbookModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateOrderbookModel
        //private CreateOrderbookModel instance;

        public CreateOrderbookModelTests()
        {
            // TODO uncomment below to create an instance of CreateOrderbookModel
            //instance = new CreateOrderbookModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateOrderbookModel
        /// </summary>
        [Fact]
        public void CreateOrderbookModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateOrderbookModel
            //Assert.IsType<CreateOrderbookModel>(instance);
        }


        /// <summary>
        /// Test the property 'BaseAssetId'
        /// </summary>
        [Fact]
        public void BaseAssetIdTest()
        {
            // TODO unit test for the property 'BaseAssetId'
        }
        /// <summary>
        /// Test the property 'QuoteAssetId'
        /// </summary>
        [Fact]
        public void QuoteAssetIdTest()
        {
            // TODO unit test for the property 'QuoteAssetId'
        }
        /// <summary>
        /// Test the property 'BaseAssetPrecision'
        /// </summary>
        [Fact]
        public void BaseAssetPrecisionTest()
        {
            // TODO unit test for the property 'BaseAssetPrecision'
        }
        /// <summary>
        /// Test the property 'QuoteAssetPrecision'
        /// </summary>
        [Fact]
        public void QuoteAssetPrecisionTest()
        {
            // TODO unit test for the property 'QuoteAssetPrecision'
        }

    }

}
