/*
 * StarkExpress API Docs
 *
 * An API for the StarkExpress platform.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using StarkExpress.SDK.Client.Api;
using StarkExpress.SDK.Client.Model;
using StarkExpress.SDK.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace StarkExpress.SDK.Client.Test.Model
{
    /// <summary>
    ///  Class for testing DataAvailabilityModes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DataAvailabilityModesTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DataAvailabilityModes
        //private DataAvailabilityModes instance;

        public DataAvailabilityModesTests()
        {
            // TODO uncomment below to create an instance of DataAvailabilityModes
            //instance = new DataAvailabilityModes();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DataAvailabilityModes
        /// </summary>
        [Fact]
        public void DataAvailabilityModesInstanceTest()
        {
            // TODO uncomment below to test "IsType" DataAvailabilityModes
            //Assert.IsType<DataAvailabilityModes>(instance);
        }



    }

}
