/*
 * StarkExpress API Docs
 *
 * An API for the StarkExpress platform.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using StarkExpress.SDK.Client.Api;
using StarkExpress.SDK.Client.Model;
using StarkExpress.SDK.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace StarkExpress.SDK.Client.Test.Model
{
    /// <summary>
    ///  Class for testing DomainDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DomainDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DomainDto
        //private DomainDto instance;

        public DomainDtoTests()
        {
            // TODO uncomment below to create an instance of DomainDto
            //instance = new DomainDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DomainDto
        /// </summary>
        [Fact]
        public void DomainDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" DomainDto
            //Assert.IsType<DomainDto>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property '_Version'
        /// </summary>
        [Fact]
        public void _VersionTest()
        {
            // TODO unit test for the property '_Version'
        }
        /// <summary>
        /// Test the property 'ChainId'
        /// </summary>
        [Fact]
        public void ChainIdTest()
        {
            // TODO unit test for the property 'ChainId'
        }
        /// <summary>
        /// Test the property 'VerifyingContract'
        /// </summary>
        [Fact]
        public void VerifyingContractTest()
        {
            // TODO unit test for the property 'VerifyingContract'
        }

    }

}
