/*
 * StarkExpress API Docs
 *
 * An API for the StarkExpress platform.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using StarkExpress.SDK.Client.Api;
using StarkExpress.SDK.Client.Model;
using StarkExpress.SDK.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace StarkExpress.SDK.Client.Test.Model
{
    /// <summary>
    ///  Class for testing EnableAssetModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EnableAssetModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EnableAssetModel
        //private EnableAssetModel instance;

        public EnableAssetModelTests()
        {
            // TODO uncomment below to create an instance of EnableAssetModel
            //instance = new EnableAssetModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EnableAssetModel
        /// </summary>
        [Fact]
        public void EnableAssetModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" EnableAssetModel
            //Assert.IsType<EnableAssetModel>(instance);
        }


        /// <summary>
        /// Test the property 'AssetId'
        /// </summary>
        [Fact]
        public void AssetIdTest()
        {
            // TODO unit test for the property 'AssetId'
        }

    }

}
