/*
 * StarkExpress API Docs
 *
 * An API for the StarkExpress platform.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using StarkExpress.SDK.Client.Api;
using StarkExpress.SDK.Client.Model;
using StarkExpress.SDK.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace StarkExpress.SDK.Client.Test.Model
{
    /// <summary>
    ///  Class for testing FeeAction
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FeeActionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FeeAction
        //private FeeAction instance;

        public FeeActionTests()
        {
            // TODO uncomment below to create an instance of FeeAction
            //instance = new FeeAction();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FeeAction
        /// </summary>
        [Fact]
        public void FeeActionInstanceTest()
        {
            // TODO uncomment below to test "IsType" FeeAction
            //Assert.IsType<FeeAction>(instance);
        }



    }

}
