/*
 * StarkExpress API Docs
 *
 * An API for the StarkExpress platform.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using StarkExpress.SDK.Client.Api;
using StarkExpress.SDK.Client.Model;
using StarkExpress.SDK.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace StarkExpress.SDK.Client.Test.Model
{
    /// <summary>
    ///  Class for testing MemberDescriptionDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MemberDescriptionDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MemberDescriptionDto
        //private MemberDescriptionDto instance;

        public MemberDescriptionDtoTests()
        {
            // TODO uncomment below to create an instance of MemberDescriptionDto
            //instance = new MemberDescriptionDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MemberDescriptionDto
        /// </summary>
        [Fact]
        public void MemberDescriptionDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" MemberDescriptionDto
            //Assert.IsType<MemberDescriptionDto>(instance);
        }


        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

    }

}
