/*
 * StarkExpress API Docs
 *
 * An API for the StarkExpress platform.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using StarkExpress.SDK.Client.Api;
using StarkExpress.SDK.Client.Model;
using StarkExpress.SDK.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace StarkExpress.SDK.Client.Test.Model
{
    /// <summary>
    ///  Class for testing MintDataModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MintDataModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MintDataModel
        //private MintDataModel instance;

        public MintDataModelTests()
        {
            // TODO uncomment below to create an instance of MintDataModel
            //instance = new MintDataModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MintDataModel
        /// </summary>
        [Fact]
        public void MintDataModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" MintDataModel
            //Assert.IsType<MintDataModel>(instance);
        }


        /// <summary>
        /// Test the property 'MintingBlob'
        /// </summary>
        [Fact]
        public void MintingBlobTest()
        {
            // TODO unit test for the property 'MintingBlob'
        }
        /// <summary>
        /// Test the property 'AssetId'
        /// </summary>
        [Fact]
        public void AssetIdTest()
        {
            // TODO unit test for the property 'AssetId'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }
        /// <summary>
        /// Test the property 'DataAvailabilityMode'
        /// </summary>
        [Fact]
        public void DataAvailabilityModeTest()
        {
            // TODO unit test for the property 'DataAvailabilityMode'
        }

    }

}
