/*
 * Arc API Docs
 *
 * An API for the Arc platform.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using StarkExpress.SDK.Client.Api;
using StarkExpress.SDK.Client.Model;
using StarkExpress.SDK.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace StarkExpress.SDK.Client.Test.Model
{
    /// <summary>
    ///  Class for testing OfferDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OfferDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OfferDto
        //private OfferDto instance;

        public OfferDtoTests()
        {
            // TODO uncomment below to create an instance of OfferDto
            //instance = new OfferDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OfferDto
        /// </summary>
        [Fact]
        public void OfferDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" OfferDto
            //Assert.IsType<OfferDto>(instance);
        }


        /// <summary>
        /// Test the property 'OfferId'
        /// </summary>
        [Fact]
        public void OfferIdTest()
        {
            // TODO unit test for the property 'OfferId'
        }
        /// <summary>
        /// Test the property 'ProductId'
        /// </summary>
        [Fact]
        public void ProductIdTest()
        {
            // TODO unit test for the property 'ProductId'
        }
        /// <summary>
        /// Test the property 'Quantity'
        /// </summary>
        [Fact]
        public void QuantityTest()
        {
            // TODO unit test for the property 'Quantity'
        }
        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Fact]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }
        /// <summary>
        /// Test the property 'CreationDate'
        /// </summary>
        [Fact]
        public void CreationDateTest()
        {
            // TODO unit test for the property 'CreationDate'
        }
        /// <summary>
        /// Test the property 'ClosingDate'
        /// </summary>
        [Fact]
        public void ClosingDateTest()
        {
            // TODO unit test for the property 'ClosingDate'
        }

    }

}
