/*
 * StarkExpress API Docs
 *
 * An API for the StarkExpress platform.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using StarkExpress.SDK.Client.Api;
using StarkExpress.SDK.Client.Model;
using StarkExpress.SDK.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace StarkExpress.SDK.Client.Test.Model
{
    /// <summary>
    ///  Class for testing OrderbookLevel2EntryDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderbookLevel2EntryDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderbookLevel2EntryDto
        //private OrderbookLevel2EntryDto instance;

        public OrderbookLevel2EntryDtoTests()
        {
            // TODO uncomment below to create an instance of OrderbookLevel2EntryDto
            //instance = new OrderbookLevel2EntryDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderbookLevel2EntryDto
        /// </summary>
        [Fact]
        public void OrderbookLevel2EntryDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderbookLevel2EntryDto
            //Assert.IsType<OrderbookLevel2EntryDto>(instance);
        }


        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Fact]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }
        /// <summary>
        /// Test the property 'Amount'
        /// </summary>
        [Fact]
        public void AmountTest()
        {
            // TODO unit test for the property 'Amount'
        }

    }

}
