/*
 * StarkExpress API Docs
 *
 * An API for the StarkExpress platform.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using StarkExpress.SDK.Client.Api;
using StarkExpress.SDK.Client.Model;
using StarkExpress.SDK.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace StarkExpress.SDK.Client.Test.Model
{
    /// <summary>
    ///  Class for testing OrderDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderDto
        //private OrderDto instance;

        public OrderDtoTests()
        {
            // TODO uncomment below to create an instance of OrderDto
            //instance = new OrderDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderDto
        /// </summary>
        [Fact]
        public void OrderDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderDto
            //Assert.IsType<OrderDto>(instance);
        }


        /// <summary>
        /// Test the property 'OrderId'
        /// </summary>
        [Fact]
        public void OrderIdTest()
        {
            // TODO unit test for the property 'OrderId'
        }
        /// <summary>
        /// Test the property 'OrderbookId'
        /// </summary>
        [Fact]
        public void OrderbookIdTest()
        {
            // TODO unit test for the property 'OrderbookId'
        }
        /// <summary>
        /// Test the property 'Price'
        /// </summary>
        [Fact]
        public void PriceTest()
        {
            // TODO unit test for the property 'Price'
        }
        /// <summary>
        /// Test the property 'OriginalAmount'
        /// </summary>
        [Fact]
        public void OriginalAmountTest()
        {
            // TODO unit test for the property 'OriginalAmount'
        }
        /// <summary>
        /// Test the property 'ExecutedAmount'
        /// </summary>
        [Fact]
        public void ExecutedAmountTest()
        {
            // TODO unit test for the property 'ExecutedAmount'
        }
        /// <summary>
        /// Test the property 'Fills'
        /// </summary>
        [Fact]
        public void FillsTest()
        {
            // TODO unit test for the property 'Fills'
        }

    }

}
