/*
 * StarkExpress API Docs
 *
 * An API for the StarkExpress platform.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using StarkExpress.SDK.Client.Api;
using StarkExpress.SDK.Client.Model;
using StarkExpress.SDK.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace StarkExpress.SDK.Client.Test.Model
{
    /// <summary>
    ///  Class for testing OrderSide
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OrderSideTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OrderSide
        //private OrderSide instance;

        public OrderSideTests()
        {
            // TODO uncomment below to create an instance of OrderSide
            //instance = new OrderSide();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OrderSide
        /// </summary>
        [Fact]
        public void OrderSideInstanceTest()
        {
            // TODO uncomment below to test "IsType" OrderSide
            //Assert.IsType<OrderSide>(instance);
        }



    }

}
