/*
 * Arc API Docs
 *
 * An API for the Arc platform.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using StarkExpress.SDK.Client.Api;
using StarkExpress.SDK.Client.Model;
using StarkExpress.SDK.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace StarkExpress.SDK.Client.Test.Model
{
    /// <summary>
    ///  Class for testing PaginationDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PaginationDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PaginationDto
        //private PaginationDto instance;

        public PaginationDtoTests()
        {
            // TODO uncomment below to create an instance of PaginationDto
            //instance = new PaginationDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PaginationDto
        /// </summary>
        [Fact]
        public void PaginationDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" PaginationDto
            //Assert.IsType<PaginationDto>(instance);
        }


        /// <summary>
        /// Test the property 'PageNumber'
        /// </summary>
        [Fact]
        public void PageNumberTest()
        {
            // TODO unit test for the property 'PageNumber'
        }
        /// <summary>
        /// Test the property 'PageSize'
        /// </summary>
        [Fact]
        public void PageSizeTest()
        {
            // TODO unit test for the property 'PageSize'
        }
        /// <summary>
        /// Test the property 'HasNext'
        /// </summary>
        [Fact]
        public void HasNextTest()
        {
            // TODO unit test for the property 'HasNext'
        }

    }

}
