/*
 * Arc API Docs
 *
 * An API for the Arc platform.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using StarkExpress.SDK.Client.Api;
using StarkExpress.SDK.Client.Model;
using StarkExpress.SDK.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace StarkExpress.SDK.Client.Test.Model
{
    /// <summary>
    ///  Class for testing RegisterBuyOrderModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RegisterBuyOrderModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RegisterBuyOrderModel
        //private RegisterBuyOrderModel instance;

        public RegisterBuyOrderModelTests()
        {
            // TODO uncomment below to create an instance of RegisterBuyOrderModel
            //instance = new RegisterBuyOrderModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RegisterBuyOrderModel
        /// </summary>
        [Fact]
        public void RegisterBuyOrderModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" RegisterBuyOrderModel
            //Assert.IsType<RegisterBuyOrderModel>(instance);
        }


        /// <summary>
        /// Test the property 'OfferId'
        /// </summary>
        [Fact]
        public void OfferIdTest()
        {
            // TODO unit test for the property 'OfferId'
        }
        /// <summary>
        /// Test the property 'BuyerId'
        /// </summary>
        [Fact]
        public void BuyerIdTest()
        {
            // TODO unit test for the property 'BuyerId'
        }
        /// <summary>
        /// Test the property 'ProductVaultId'
        /// </summary>
        [Fact]
        public void ProductVaultIdTest()
        {
            // TODO unit test for the property 'ProductVaultId'
        }
        /// <summary>
        /// Test the property 'CurrencyVaultId'
        /// </summary>
        [Fact]
        public void CurrencyVaultIdTest()
        {
            // TODO unit test for the property 'CurrencyVaultId'
        }
        /// <summary>
        /// Test the property 'ExpirationTimestamp'
        /// </summary>
        [Fact]
        public void ExpirationTimestampTest()
        {
            // TODO unit test for the property 'ExpirationTimestamp'
        }
        /// <summary>
        /// Test the property 'Nonce'
        /// </summary>
        [Fact]
        public void NonceTest()
        {
            // TODO unit test for the property 'Nonce'
        }
        /// <summary>
        /// Test the property 'Signature'
        /// </summary>
        [Fact]
        public void SignatureTest()
        {
            // TODO unit test for the property 'Signature'
        }

    }

}
