/*
 * StarkExpress API Docs
 *
 * An API for the StarkExpress platform.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using StarkExpress.SDK.Client.Api;
using StarkExpress.SDK.Client.Model;
using StarkExpress.SDK.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace StarkExpress.SDK.Client.Test.Model
{
    /// <summary>
    ///  Class for testing RegisterDetailsDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RegisterDetailsDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RegisterDetailsDto
        //private RegisterDetailsDto instance;

        public RegisterDetailsDtoTests()
        {
            // TODO uncomment below to create an instance of RegisterDetailsDto
            //instance = new RegisterDetailsDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RegisterDetailsDto
        /// </summary>
        [Fact]
        public void RegisterDetailsDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" RegisterDetailsDto
            //Assert.IsType<RegisterDetailsDto>(instance);
        }


        /// <summary>
        /// Test the property 'Domain'
        /// </summary>
        [Fact]
        public void DomainTest()
        {
            // TODO unit test for the property 'Domain'
        }
        /// <summary>
        /// Test the property 'Types'
        /// </summary>
        [Fact]
        public void TypesTest()
        {
            // TODO unit test for the property 'Types'
        }
        /// <summary>
        /// Test the property 'PrimaryType'
        /// </summary>
        [Fact]
        public void PrimaryTypeTest()
        {
            // TODO unit test for the property 'PrimaryType'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'DomainRawValues'
        /// </summary>
        [Fact]
        public void DomainRawValuesTest()
        {
            // TODO unit test for the property 'DomainRawValues'
        }

    }

}
