/*
 * StarkExpress API Docs
 *
 * An API for the StarkExpress platform.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using StarkExpress.SDK.Client.Api;
using StarkExpress.SDK.Client.Model;
using StarkExpress.SDK.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace StarkExpress.SDK.Client.Test.Model
{
    /// <summary>
    ///  Class for testing SettlementOrderModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SettlementOrderModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SettlementOrderModel
        //private SettlementOrderModel instance;

        public SettlementOrderModelTests()
        {
            // TODO uncomment below to create an instance of SettlementOrderModel
            //instance = new SettlementOrderModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SettlementOrderModel
        /// </summary>
        [Fact]
        public void SettlementOrderModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" SettlementOrderModel
            //Assert.IsType<SettlementOrderModel>(instance);
        }


        /// <summary>
        /// Test the property 'BuyVaultId'
        /// </summary>
        [Fact]
        public void BuyVaultIdTest()
        {
            // TODO unit test for the property 'BuyVaultId'
        }
        /// <summary>
        /// Test the property 'BuyQuantizedAmount'
        /// </summary>
        [Fact]
        public void BuyQuantizedAmountTest()
        {
            // TODO unit test for the property 'BuyQuantizedAmount'
        }
        /// <summary>
        /// Test the property 'SellVaultId'
        /// </summary>
        [Fact]
        public void SellVaultIdTest()
        {
            // TODO unit test for the property 'SellVaultId'
        }
        /// <summary>
        /// Test the property 'SellQuantizedAmount'
        /// </summary>
        [Fact]
        public void SellQuantizedAmountTest()
        {
            // TODO unit test for the property 'SellQuantizedAmount'
        }
        /// <summary>
        /// Test the property 'FeeVaultId'
        /// </summary>
        [Fact]
        public void FeeVaultIdTest()
        {
            // TODO unit test for the property 'FeeVaultId'
        }
        /// <summary>
        /// Test the property 'FeeQuantizedAmount'
        /// </summary>
        [Fact]
        public void FeeQuantizedAmountTest()
        {
            // TODO unit test for the property 'FeeQuantizedAmount'
        }
        /// <summary>
        /// Test the property 'Nonce'
        /// </summary>
        [Fact]
        public void NonceTest()
        {
            // TODO unit test for the property 'Nonce'
        }
        /// <summary>
        /// Test the property 'Signature'
        /// </summary>
        [Fact]
        public void SignatureTest()
        {
            // TODO unit test for the property 'Signature'
        }
        /// <summary>
        /// Test the property 'ExpirationTimestamp'
        /// </summary>
        [Fact]
        public void ExpirationTimestampTest()
        {
            // TODO unit test for the property 'ExpirationTimestamp'
        }

    }

}
