/*
 * StarkExpress API Docs
 *
 * An API for the StarkExpress platform.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using StarkExpress.SDK.Client.Api;
using StarkExpress.SDK.Client.Model;
using StarkExpress.SDK.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace StarkExpress.SDK.Client.Test.Model
{
    /// <summary>
    ///  Class for testing SignatureModel
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SignatureModelTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SignatureModel
        //private SignatureModel instance;

        public SignatureModelTests()
        {
            // TODO uncomment below to create an instance of SignatureModel
            //instance = new SignatureModel();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SignatureModel
        /// </summary>
        [Fact]
        public void SignatureModelInstanceTest()
        {
            // TODO uncomment below to test "IsType" SignatureModel
            //Assert.IsType<SignatureModel>(instance);
        }


        /// <summary>
        /// Test the property 'R'
        /// </summary>
        [Fact]
        public void RTest()
        {
            // TODO unit test for the property 'R'
        }
        /// <summary>
        /// Test the property 'S'
        /// </summary>
        [Fact]
        public void STest()
        {
            // TODO unit test for the property 'S'
        }

    }

}
