/*
 * StarkExpress API Docs
 *
 * An API for the StarkExpress platform.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using StarkExpress.SDK.Client.Model;
using StarkExpress.SDK.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace StarkExpress.SDK.Client.Test.Model
{
    /// <summary>
    ///  Class for testing StarkExOperation
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StarkExOperationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for StarkExOperation
        //private StarkExOperation instance;

        public StarkExOperationTests()
        {
            // TODO uncomment below to create an instance of StarkExOperation
            //instance = new StarkExOperation();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of StarkExOperation
        /// </summary>
        [Fact]
        public void StarkExOperationInstanceTest()
        {
            // TODO uncomment below to test "IsType" StarkExOperation
            //Assert.IsType<StarkExOperation>(instance);
        }



    }

}
