/*
 * StarkExpress API Docs
 *
 * An API for the StarkExpress platform.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using StarkExpress.SDK.Client.Api;
using StarkExpress.SDK.Client.Model;
using StarkExpress.SDK.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace StarkExpress.SDK.Client.Test.Model
{
    /// <summary>
    ///  Class for testing TransferDetailsDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TransferDetailsDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TransferDetailsDto
        //private TransferDetailsDto instance;

        public TransferDetailsDtoTests()
        {
            // TODO uncomment below to create an instance of TransferDetailsDto
            //instance = new TransferDetailsDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TransferDetailsDto
        /// </summary>
        [Fact]
        public void TransferDetailsDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" TransferDetailsDto
            //Assert.IsType<TransferDetailsDto>(instance);
        }


        /// <summary>
        /// Test the property 'SenderStarkKey'
        /// </summary>
        [Fact]
        public void SenderStarkKeyTest()
        {
            // TODO unit test for the property 'SenderStarkKey'
        }
        /// <summary>
        /// Test the property 'SenderVaultChainId'
        /// </summary>
        [Fact]
        public void SenderVaultChainIdTest()
        {
            // TODO unit test for the property 'SenderVaultChainId'
        }
        /// <summary>
        /// Test the property 'SenderVaultId'
        /// </summary>
        [Fact]
        public void SenderVaultIdTest()
        {
            // TODO unit test for the property 'SenderVaultId'
        }
        /// <summary>
        /// Test the property 'ReceiverStarkKey'
        /// </summary>
        [Fact]
        public void ReceiverStarkKeyTest()
        {
            // TODO unit test for the property 'ReceiverStarkKey'
        }
        /// <summary>
        /// Test the property 'ReceiverVaultChainId'
        /// </summary>
        [Fact]
        public void ReceiverVaultChainIdTest()
        {
            // TODO unit test for the property 'ReceiverVaultChainId'
        }
        /// <summary>
        /// Test the property 'ReceiverVaultId'
        /// </summary>
        [Fact]
        public void ReceiverVaultIdTest()
        {
            // TODO unit test for the property 'ReceiverVaultId'
        }
        /// <summary>
        /// Test the property 'AssetId'
        /// </summary>
        [Fact]
        public void AssetIdTest()
        {
            // TODO unit test for the property 'AssetId'
        }
        /// <summary>
        /// Test the property 'QuantizedAmount'
        /// </summary>
        [Fact]
        public void QuantizedAmountTest()
        {
            // TODO unit test for the property 'QuantizedAmount'
        }
        /// <summary>
        /// Test the property 'FeeVaultChainId'
        /// </summary>
        [Fact]
        public void FeeVaultChainIdTest()
        {
            // TODO unit test for the property 'FeeVaultChainId'
        }
        /// <summary>
        /// Test the property 'FeeVaultId'
        /// </summary>
        [Fact]
        public void FeeVaultIdTest()
        {
            // TODO unit test for the property 'FeeVaultId'
        }
        /// <summary>
        /// Test the property 'FeeQuantizedAmount'
        /// </summary>
        [Fact]
        public void FeeQuantizedAmountTest()
        {
            // TODO unit test for the property 'FeeQuantizedAmount'
        }
        /// <summary>
        /// Test the property 'FeeAssetId'
        /// </summary>
        [Fact]
        public void FeeAssetIdTest()
        {
            // TODO unit test for the property 'FeeAssetId'
        }
        /// <summary>
        /// Test the property 'ExpirationTimestamp'
        /// </summary>
        [Fact]
        public void ExpirationTimestampTest()
        {
            // TODO unit test for the property 'ExpirationTimestamp'
        }
        /// <summary>
        /// Test the property 'Nonce'
        /// </summary>
        [Fact]
        public void NonceTest()
        {
            // TODO unit test for the property 'Nonce'
        }
        /// <summary>
        /// Test the property 'SignablePayload'
        /// </summary>
        [Fact]
        public void SignablePayloadTest()
        {
            // TODO unit test for the property 'SignablePayload'
        }

    }

}
