/*
 * Arc API Docs
 *
 * An API for the Arc platform.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using StarkExpress.SDK.Client.Api;
using StarkExpress.SDK.Client.Model;
using StarkExpress.SDK.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace StarkExpress.SDK.Client.Test.Model
{
    /// <summary>
    ///  Class for testing UserWithVaultsDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UserWithVaultsDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UserWithVaultsDto
        //private UserWithVaultsDto instance;

        public UserWithVaultsDtoTests()
        {
            // TODO uncomment below to create an instance of UserWithVaultsDto
            //instance = new UserWithVaultsDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UserWithVaultsDto
        /// </summary>
        [Fact]
        public void UserWithVaultsDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" UserWithVaultsDto
            //Assert.IsType<UserWithVaultsDto>(instance);
        }


        /// <summary>
        /// Test the property 'User'
        /// </summary>
        [Fact]
        public void UserTest()
        {
            // TODO unit test for the property 'User'
        }
        /// <summary>
        /// Test the property 'VaultsPerAsset'
        /// </summary>
        [Fact]
        public void VaultsPerAssetTest()
        {
            // TODO unit test for the property 'VaultsPerAsset'
        }

    }

}
