/*
 * Arc API Docs
 *
 * An API for the Arc platform.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using StarkExpress.SDK.Client.Api;
using StarkExpress.SDK.Client.Model;
using StarkExpress.SDK.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace StarkExpress.SDK.Client.Test.Model
{
    /// <summary>
    ///  Class for testing UserDtoPaginatedResponseDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UserDtoPaginatedResponseDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UserDtoPaginatedResponseDto
        //private UserDtoPaginatedResponseDto instance;

        public UserDtoPaginatedResponseDtoTests()
        {
            // TODO uncomment below to create an instance of UserDtoPaginatedResponseDto
            //instance = new UserDtoPaginatedResponseDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UserDtoPaginatedResponseDto
        /// </summary>
        [Fact]
        public void UserDtoPaginatedResponseDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" UserDtoPaginatedResponseDto
            //Assert.IsType<UserDtoPaginatedResponseDto>(instance);
        }


        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
        /// <summary>
        /// Test the property 'Pagination'
        /// </summary>
        [Fact]
        public void PaginationTest()
        {
            // TODO unit test for the property 'Pagination'
        }
        /// <summary>
        /// Test the property 'TotalCount'
        /// </summary>
        [Fact]
        public void TotalCountTest()
        {
            // TODO unit test for the property 'TotalCount'
        }

    }

}
