/*
 * Arc API Docs
 *
 * An API for the Arc platform.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using StarkExpress.SDK.Client.Api;
using StarkExpress.SDK.Client.Model;
using StarkExpress.SDK.Client.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace StarkExpress.SDK.Client.Test.Model
{
    /// <summary>
    ///  Class for testing WithdrawDetailsDto
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WithdrawDetailsDtoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WithdrawDetailsDto
        //private WithdrawDetailsDto instance;

        public WithdrawDetailsDtoTests()
        {
            // TODO uncomment below to create an instance of WithdrawDetailsDto
            //instance = new WithdrawDetailsDto();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WithdrawDetailsDto
        /// </summary>
        [Fact]
        public void WithdrawDetailsDtoInstanceTest()
        {
            // TODO uncomment below to test "IsType" WithdrawDetailsDto
            //Assert.IsType<WithdrawDetailsDto>(instance);
        }


        /// <summary>
        /// Test the property 'Vault'
        /// </summary>
        [Fact]
        public void VaultTest()
        {
            // TODO unit test for the property 'Vault'
        }
        /// <summary>
        /// Test the property 'OperatorContractAddress'
        /// </summary>
        [Fact]
        public void OperatorContractAddressTest()
        {
            // TODO unit test for the property 'OperatorContractAddress'
        }
        /// <summary>
        /// Test the property 'WithdrawFunction'
        /// </summary>
        [Fact]
        public void WithdrawFunctionTest()
        {
            // TODO unit test for the property 'WithdrawFunction'
        }
        /// <summary>
        /// Test the property 'StarkKey'
        /// </summary>
        [Fact]
        public void StarkKeyTest()
        {
            // TODO unit test for the property 'StarkKey'
        }
        /// <summary>
        /// Test the property 'AssetType'
        /// </summary>
        [Fact]
        public void AssetTypeTest()
        {
            // TODO unit test for the property 'AssetType'
        }
        /// <summary>
        /// Test the property 'TokenId'
        /// </summary>
        [Fact]
        public void TokenIdTest()
        {
            // TODO unit test for the property 'TokenId'
        }
        /// <summary>
        /// Test the property 'MintingBlob'
        /// </summary>
        [Fact]
        public void MintingBlobTest()
        {
            // TODO unit test for the property 'MintingBlob'
        }

    }

}
