/*
 * Arc API Docs
 *
 * An API for the Arc platform.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = StarkExpress.SDK.Client.Client.FileParameter;
using OpenAPIDateConverter = StarkExpress.SDK.Client.Client.OpenAPIDateConverter;

namespace StarkExpress.SDK.Client.Model
{
    /// <summary>
    /// Request model to mint a batch of assets.
    /// </summary>
    [DataContract(Name = "BatchMintRequestModel")]
    public partial class BatchMintRequestModel : IEquatable<BatchMintRequestModel>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BatchMintRequestModel" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected BatchMintRequestModel() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="BatchMintRequestModel" /> class.
        /// </summary>
        /// <param name="users">The array of assets to mint grouped by user. (required).</param>
        public BatchMintRequestModel(List<MintRequestDataModel> users = default(List<MintRequestDataModel>))
        {
            // to ensure "users" is required (not null)
            if (users == null)
            {
                throw new ArgumentNullException("users is a required property for BatchMintRequestModel and cannot be null");
            }
            this.Users = users;
        }

        /// <summary>
        /// The array of assets to mint grouped by user.
        /// </summary>
        /// <value>The array of assets to mint grouped by user.</value>
        [DataMember(Name = "users", IsRequired = true, EmitDefaultValue = true)]
        public List<MintRequestDataModel> Users { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BatchMintRequestModel {\n");
            sb.Append("  Users: ").Append(Users).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as BatchMintRequestModel);
        }

        /// <summary>
        /// Returns true if BatchMintRequestModel instances are equal
        /// </summary>
        /// <param name="input">Instance of BatchMintRequestModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BatchMintRequestModel input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.Users == input.Users ||
                    this.Users != null &&
                    input.Users != null &&
                    this.Users.SequenceEqual(input.Users)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Users != null)
                {
                    hashCode = (hashCode * 59) + this.Users.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
