/*
 * StarkExpress API Docs
 *
 * An API for the StarkExpress platform.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = StarkExpress.SDK.Client.Client.OpenAPIDateConverter;

namespace StarkExpress.SDK.Client.Model
{
    /// <summary>
    /// DepositDetailsModel
    /// </summary>
    [DataContract(Name = "DepositDetailsModel")]
    public partial class DepositDetailsModel : IEquatable<DepositDetailsModel>, IValidatableObject
    {

        /// <summary>
        /// Gets or Sets DataAvailabilityMode
        /// </summary>
        [DataMember(Name = "dataAvailabilityMode", IsRequired = true, EmitDefaultValue = true)]
        public DataAvailabilityModes DataAvailabilityMode { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="DepositDetailsModel" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected DepositDetailsModel() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="DepositDetailsModel" /> class.
        /// </summary>
        /// <param name="userId">The ID of the user for which the vault should be allocated. (required).</param>
        /// <param name="assetId">The ID of the vault&#39;s asset. (required).</param>
        /// <param name="dataAvailabilityMode">dataAvailabilityMode (required).</param>
        /// <param name="tokenId">The hexadecimal string representation of the vault&#39;s asset token ID, if applicable (ie. ERC-721/ERC-1155)..</param>
        /// <param name="amount">The amount of the asset to be deposited. (required).</param>
        public DepositDetailsModel(Guid userId = default(Guid), Guid assetId = default(Guid), DataAvailabilityModes dataAvailabilityMode = default(DataAvailabilityModes), string tokenId = default(string), string amount = default(string))
        {
            this.UserId = userId;
            this.AssetId = assetId;
            this.DataAvailabilityMode = dataAvailabilityMode;
            // to ensure "amount" is required (not null)
            if (amount == null)
            {
                throw new ArgumentNullException("amount is a required property for DepositDetailsModel and cannot be null");
            }
            this.Amount = amount;
            this.TokenId = tokenId;
        }

        /// <summary>
        /// The ID of the user for which the vault should be allocated.
        /// </summary>
        /// <value>The ID of the user for which the vault should be allocated.</value>
        [DataMember(Name = "userId", IsRequired = true, EmitDefaultValue = true)]
        public Guid UserId { get; set; }

        /// <summary>
        /// The ID of the vault&#39;s asset.
        /// </summary>
        /// <value>The ID of the vault&#39;s asset.</value>
        [DataMember(Name = "assetId", IsRequired = true, EmitDefaultValue = true)]
        public Guid AssetId { get; set; }

        /// <summary>
        /// The hexadecimal string representation of the vault&#39;s asset token ID, if applicable (ie. ERC-721/ERC-1155).
        /// </summary>
        /// <value>The hexadecimal string representation of the vault&#39;s asset token ID, if applicable (ie. ERC-721/ERC-1155).</value>
        [DataMember(Name = "tokenId", EmitDefaultValue = true)]
        public string TokenId { get; set; }

        /// <summary>
        /// The amount of the asset to be deposited.
        /// </summary>
        /// <value>The amount of the asset to be deposited.</value>
        [DataMember(Name = "amount", IsRequired = true, EmitDefaultValue = true)]
        public string Amount { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DepositDetailsModel {\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("  AssetId: ").Append(AssetId).Append("\n");
            sb.Append("  DataAvailabilityMode: ").Append(DataAvailabilityMode).Append("\n");
            sb.Append("  TokenId: ").Append(TokenId).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as DepositDetailsModel);
        }

        /// <summary>
        /// Returns true if DepositDetailsModel instances are equal
        /// </summary>
        /// <param name="input">Instance of DepositDetailsModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(DepositDetailsModel input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.UserId == input.UserId ||
                    (this.UserId != null &&
                    this.UserId.Equals(input.UserId))
                ) && 
                (
                    this.AssetId == input.AssetId ||
                    (this.AssetId != null &&
                    this.AssetId.Equals(input.AssetId))
                ) && 
                (
                    this.DataAvailabilityMode == input.DataAvailabilityMode ||
                    this.DataAvailabilityMode.Equals(input.DataAvailabilityMode)
                ) && 
                (
                    this.TokenId == input.TokenId ||
                    (this.TokenId != null &&
                    this.TokenId.Equals(input.TokenId))
                ) && 
                (
                    this.Amount == input.Amount ||
                    (this.Amount != null &&
                    this.Amount.Equals(input.Amount))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.UserId != null)
                {
                    hashCode = (hashCode * 59) + this.UserId.GetHashCode();
                }
                if (this.AssetId != null)
                {
                    hashCode = (hashCode * 59) + this.AssetId.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.DataAvailabilityMode.GetHashCode();
                if (this.TokenId != null)
                {
                    hashCode = (hashCode * 59) + this.TokenId.GetHashCode();
                }
                if (this.Amount != null)
                {
                    hashCode = (hashCode * 59) + this.Amount.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
