/*
 * Arc API Docs
 *
 * An API for the Arc platform.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using FileParameter = StarkExpress.SDK.Client.Client.FileParameter;
using OpenAPIDateConverter = StarkExpress.SDK.Client.Client.OpenAPIDateConverter;

namespace StarkExpress.SDK.Client.Model
{
    /// <summary>
    /// Request model to enable an asset in the tenant system.
    /// </summary>
    [DataContract(Name = "EnableAssetModel")]
    public partial class EnableAssetModel : IEquatable<EnableAssetModel>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EnableAssetModel" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected EnableAssetModel() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="EnableAssetModel" /> class.
        /// </summary>
        /// <param name="assetId">The unique identifier of the asset to enable. (required).</param>
        public EnableAssetModel(Guid assetId = default(Guid))
        {
            this.AssetId = assetId;
        }

        /// <summary>
        /// The unique identifier of the asset to enable.
        /// </summary>
        /// <value>The unique identifier of the asset to enable.</value>
        [DataMember(Name = "assetId", IsRequired = true, EmitDefaultValue = true)]
        public Guid AssetId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EnableAssetModel {\n");
            sb.Append("  AssetId: ").Append(AssetId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as EnableAssetModel);
        }

        /// <summary>
        /// Returns true if EnableAssetModel instances are equal
        /// </summary>
        /// <param name="input">Instance of EnableAssetModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EnableAssetModel input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.AssetId == input.AssetId ||
                    (this.AssetId != null &&
                    this.AssetId.Equals(input.AssetId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.AssetId != null)
                {
                    hashCode = (hashCode * 59) + this.AssetId.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
