/*
 * StarkExpress API Docs
 *
 * An API for the StarkExpress platform.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = StarkExpress.SDK.Client.Client.OpenAPIDateConverter;

namespace StarkExpress.SDK.Client.Model
{
    /// <summary>
    /// Defines ErrorCodes
    /// </summary>
    public enum ErrorCodes
    {
        /// <summary>
        /// Enum NUMBER_10000 for value: 10000
        /// </summary>
        NUMBER_10000 = 10000,

        /// <summary>
        /// Enum NUMBER_10001 for value: 10001
        /// </summary>
        NUMBER_10001 = 10001,

        /// <summary>
        /// Enum NUMBER_10002 for value: 10002
        /// </summary>
        NUMBER_10002 = 10002,

        /// <summary>
        /// Enum NUMBER_10101 for value: 10101
        /// </summary>
        NUMBER_10101 = 10101,

        /// <summary>
        /// Enum NUMBER_10102 for value: 10102
        /// </summary>
        NUMBER_10102 = 10102,

        /// <summary>
        /// Enum NUMBER_10103 for value: 10103
        /// </summary>
        NUMBER_10103 = 10103,

        /// <summary>
        /// Enum NUMBER_10104 for value: 10104
        /// </summary>
        NUMBER_10104 = 10104,

        /// <summary>
        /// Enum NUMBER_10105 for value: 10105
        /// </summary>
        NUMBER_10105 = 10105,

        /// <summary>
        /// Enum NUMBER_10106 for value: 10106
        /// </summary>
        NUMBER_10106 = 10106,

        /// <summary>
        /// Enum NUMBER_10201 for value: 10201
        /// </summary>
        NUMBER_10201 = 10201,

        /// <summary>
        /// Enum NUMBER_10202 for value: 10202
        /// </summary>
        NUMBER_10202 = 10202,

        /// <summary>
        /// Enum NUMBER_10203 for value: 10203
        /// </summary>
        NUMBER_10203 = 10203,

        /// <summary>
        /// Enum NUMBER_10301 for value: 10301
        /// </summary>
        NUMBER_10301 = 10301,

        /// <summary>
        /// Enum NUMBER_10302 for value: 10302
        /// </summary>
        NUMBER_10302 = 10302,

        /// <summary>
        /// Enum NUMBER_10303 for value: 10303
        /// </summary>
        NUMBER_10303 = 10303,

        /// <summary>
        /// Enum NUMBER_10304 for value: 10304
        /// </summary>
        NUMBER_10304 = 10304,

        /// <summary>
        /// Enum NUMBER_10401 for value: 10401
        /// </summary>
        NUMBER_10401 = 10401,

        /// <summary>
        /// Enum NUMBER_10402 for value: 10402
        /// </summary>
        NUMBER_10402 = 10402,

        /// <summary>
        /// Enum NUMBER_10403 for value: 10403
        /// </summary>
        NUMBER_10403 = 10403,

        /// <summary>
        /// Enum NUMBER_10404 for value: 10404
        /// </summary>
        NUMBER_10404 = 10404,

        /// <summary>
        /// Enum NUMBER_10501 for value: 10501
        /// </summary>
        NUMBER_10501 = 10501,

        /// <summary>
        /// Enum NUMBER_10502 for value: 10502
        /// </summary>
        NUMBER_10502 = 10502,

        /// <summary>
        /// Enum NUMBER_10601 for value: 10601
        /// </summary>
        NUMBER_10601 = 10601,

        /// <summary>
        /// Enum NUMBER_10602 for value: 10602
        /// </summary>
        NUMBER_10602 = 10602,

        /// <summary>
        /// Enum NUMBER_10603 for value: 10603
        /// </summary>
        NUMBER_10603 = 10603,

        /// <summary>
        /// Enum NUMBER_10604 for value: 10604
        /// </summary>
        NUMBER_10604 = 10604,

        /// <summary>
        /// Enum NUMBER_10605 for value: 10605
        /// </summary>
        NUMBER_10605 = 10605,

        /// <summary>
        /// Enum NUMBER_10606 for value: 10606
        /// </summary>
        NUMBER_10606 = 10606,

        /// <summary>
        /// Enum NUMBER_10607 for value: 10607
        /// </summary>
        NUMBER_10607 = 10607,

        /// <summary>
        /// Enum NUMBER_10608 for value: 10608
        /// </summary>
        NUMBER_10608 = 10608,

        /// <summary>
        /// Enum NUMBER_10609 for value: 10609
        /// </summary>
        NUMBER_10609 = 10609,

        /// <summary>
        /// Enum NUMBER_10610 for value: 10610
        /// </summary>
        NUMBER_10610 = 10610,

        /// <summary>
        /// Enum NUMBER_10611 for value: 10611
        /// </summary>
        NUMBER_10611 = 10611,

        /// <summary>
        /// Enum NUMBER_10612 for value: 10612
        /// </summary>
        NUMBER_10612 = 10612,

        /// <summary>
        /// Enum NUMBER_10613 for value: 10613
        /// </summary>
        NUMBER_10613 = 10613,

        /// <summary>
        /// Enum NUMBER_10614 for value: 10614
        /// </summary>
        NUMBER_10614 = 10614,

        /// <summary>
        /// Enum NUMBER_10701 for value: 10701
        /// </summary>
        NUMBER_10701 = 10701,

        /// <summary>
        /// Enum NUMBER_10801 for value: 10801
        /// </summary>
        NUMBER_10801 = 10801,

        /// <summary>
        /// Enum NUMBER_10802 for value: 10802
        /// </summary>
        NUMBER_10802 = 10802,

        /// <summary>
        /// Enum NUMBER_10803 for value: 10803
        /// </summary>
        NUMBER_10803 = 10803,

        /// <summary>
        /// Enum NUMBER_10901 for value: 10901
        /// </summary>
        NUMBER_10901 = 10901,

        /// <summary>
        /// Enum NUMBER_10902 for value: 10902
        /// </summary>
        NUMBER_10902 = 10902,

        /// <summary>
        /// Enum NUMBER_10903 for value: 10903
        /// </summary>
        NUMBER_10903 = 10903,

        /// <summary>
        /// Enum NUMBER_11001 for value: 11001
        /// </summary>
        NUMBER_11001 = 11001,

        /// <summary>
        /// Enum NUMBER_12001 for value: 12001
        /// </summary>
        NUMBER_12001 = 12001,

        /// <summary>
        /// Enum NUMBER_12002 for value: 12002
        /// </summary>
        NUMBER_12002 = 12002,

        /// <summary>
        /// Enum NUMBER_12003 for value: 12003
        /// </summary>
        NUMBER_12003 = 12003,

        /// <summary>
        /// Enum NUMBER_12101 for value: 12101
        /// </summary>
        NUMBER_12101 = 12101,

        /// <summary>
        /// Enum NUMBER_12102 for value: 12102
        /// </summary>
        NUMBER_12102 = 12102,

        /// <summary>
        /// Enum NUMBER_12103 for value: 12103
        /// </summary>
        NUMBER_12103 = 12103,

        /// <summary>
        /// Enum NUMBER_12104 for value: 12104
        /// </summary>
        NUMBER_12104 = 12104,

        /// <summary>
        /// Enum NUMBER_12105 for value: 12105
        /// </summary>
        NUMBER_12105 = 12105,

        /// <summary>
        /// Enum NUMBER_12201 for value: 12201
        /// </summary>
        NUMBER_12201 = 12201,

        /// <summary>
        /// Enum NUMBER_12301 for value: 12301
        /// </summary>
        NUMBER_12301 = 12301,

        /// <summary>
        /// Enum NUMBER_12302 for value: 12302
        /// </summary>
        NUMBER_12302 = 12302,

        /// <summary>
        /// Enum NUMBER_12303 for value: 12303
        /// </summary>
        NUMBER_12303 = 12303,

        /// <summary>
        /// Enum NUMBER_12304 for value: 12304
        /// </summary>
        NUMBER_12304 = 12304,

        /// <summary>
        /// Enum NUMBER_13001 for value: 13001
        /// </summary>
        NUMBER_13001 = 13001,

        /// <summary>
        /// Enum NUMBER_13002 for value: 13002
        /// </summary>
        NUMBER_13002 = 13002,

        /// <summary>
        /// Enum NUMBER_13003 for value: 13003
        /// </summary>
        NUMBER_13003 = 13003,

        /// <summary>
        /// Enum NUMBER_13004 for value: 13004
        /// </summary>
        NUMBER_13004 = 13004,

        /// <summary>
        /// Enum NUMBER_13005 for value: 13005
        /// </summary>
        NUMBER_13005 = 13005,

        /// <summary>
        /// Enum NUMBER_14001 for value: 14001
        /// </summary>
        NUMBER_14001 = 14001,

        /// <summary>
        /// Enum NUMBER_14002 for value: 14002
        /// </summary>
        NUMBER_14002 = 14002,

        /// <summary>
        /// Enum NUMBER_14003 for value: 14003
        /// </summary>
        NUMBER_14003 = 14003,

        /// <summary>
        /// Enum NUMBER_14004 for value: 14004
        /// </summary>
        NUMBER_14004 = 14004,

        /// <summary>
        /// Enum NUMBER_15001 for value: 15001
        /// </summary>
        NUMBER_15001 = 15001,

        /// <summary>
        /// Enum NUMBER_16001 for value: 16001
        /// </summary>
        NUMBER_16001 = 16001,

        /// <summary>
        /// Enum NUMBER_16002 for value: 16002
        /// </summary>
        NUMBER_16002 = 16002,

        /// <summary>
        /// Enum NUMBER_16003 for value: 16003
        /// </summary>
        NUMBER_16003 = 16003,

        /// <summary>
        /// Enum NUMBER_17001 for value: 17001
        /// </summary>
        NUMBER_17001 = 17001,

        /// <summary>
        /// Enum NUMBER_17002 for value: 17002
        /// </summary>
        NUMBER_17002 = 17002,

        /// <summary>
        /// Enum NUMBER_17003 for value: 17003
        /// </summary>
        NUMBER_17003 = 17003,

        /// <summary>
        /// Enum NUMBER_17004 for value: 17004
        /// </summary>
        NUMBER_17004 = 17004,

        /// <summary>
        /// Enum NUMBER_17005 for value: 17005
        /// </summary>
        NUMBER_17005 = 17005,

        /// <summary>
        /// Enum NUMBER_17006 for value: 17006
        /// </summary>
        NUMBER_17006 = 17006,

        /// <summary>
        /// Enum NUMBER_17007 for value: 17007
        /// </summary>
        NUMBER_17007 = 17007,

        /// <summary>
        /// Enum NUMBER_17008 for value: 17008
        /// </summary>
        NUMBER_17008 = 17008,

        /// <summary>
        /// Enum NUMBER_17009 for value: 17009
        /// </summary>
        NUMBER_17009 = 17009,

        /// <summary>
        /// Enum NUMBER_17010 for value: 17010
        /// </summary>
        NUMBER_17010 = 17010,

        /// <summary>
        /// Enum NUMBER_17011 for value: 17011
        /// </summary>
        NUMBER_17011 = 17011,

        /// <summary>
        /// Enum NUMBER_17012 for value: 17012
        /// </summary>
        NUMBER_17012 = 17012,

        /// <summary>
        /// Enum NUMBER_17013 for value: 17013
        /// </summary>
        NUMBER_17013 = 17013,

        /// <summary>
        /// Enum NUMBER_17014 for value: 17014
        /// </summary>
        NUMBER_17014 = 17014,

        /// <summary>
        /// Enum NUMBER_17015 for value: 17015
        /// </summary>
        NUMBER_17015 = 17015,

        /// <summary>
        /// Enum NUMBER_17016 for value: 17016
        /// </summary>
        NUMBER_17016 = 17016,

        /// <summary>
        /// Enum NUMBER_17017 for value: 17017
        /// </summary>
        NUMBER_17017 = 17017,

        /// <summary>
        /// Enum NUMBER_17018 for value: 17018
        /// </summary>
        NUMBER_17018 = 17018,

        /// <summary>
        /// Enum NUMBER_17019 for value: 17019
        /// </summary>
        NUMBER_17019 = 17019,

        /// <summary>
        /// Enum NUMBER_17020 for value: 17020
        /// </summary>
        NUMBER_17020 = 17020,

        /// <summary>
        /// Enum NUMBER_18001 for value: 18001
        /// </summary>
        NUMBER_18001 = 18001,

        /// <summary>
        /// Enum NUMBER_18002 for value: 18002
        /// </summary>
        NUMBER_18002 = 18002,

        /// <summary>
        /// Enum NUMBER_18003 for value: 18003
        /// </summary>
        NUMBER_18003 = 18003,

        /// <summary>
        /// Enum NUMBER_18004 for value: 18004
        /// </summary>
        NUMBER_18004 = 18004,

        /// <summary>
        /// Enum NUMBER_18005 for value: 18005
        /// </summary>
        NUMBER_18005 = 18005,

        /// <summary>
        /// Enum NUMBER_19001 for value: 19001
        /// </summary>
        NUMBER_19001 = 19001,

        /// <summary>
        /// Enum NUMBER_19002 for value: 19002
        /// </summary>
        NUMBER_19002 = 19002,

        /// <summary>
        /// Enum NUMBER_19003 for value: 19003
        /// </summary>
        NUMBER_19003 = 19003,

        /// <summary>
        /// Enum NUMBER_19004 for value: 19004
        /// </summary>
        NUMBER_19004 = 19004,

        /// <summary>
        /// Enum NUMBER_20101 for value: 20101
        /// </summary>
        NUMBER_20101 = 20101,

        /// <summary>
        /// Enum NUMBER_20301 for value: 20301
        /// </summary>
        NUMBER_20301 = 20301,

        /// <summary>
        /// Enum NUMBER_20302 for value: 20302
        /// </summary>
        NUMBER_20302 = 20302,

        /// <summary>
        /// Enum NUMBER_20303 for value: 20303
        /// </summary>
        NUMBER_20303 = 20303,

        /// <summary>
        /// Enum NUMBER_20401 for value: 20401
        /// </summary>
        NUMBER_20401 = 20401,

        /// <summary>
        /// Enum NUMBER_20501 for value: 20501
        /// </summary>
        NUMBER_20501 = 20501,

        /// <summary>
        /// Enum NUMBER_20502 for value: 20502
        /// </summary>
        NUMBER_20502 = 20502,

        /// <summary>
        /// Enum NUMBER_20601 for value: 20601
        /// </summary>
        NUMBER_20601 = 20601,

        /// <summary>
        /// Enum NUMBER_50000 for value: 50000
        /// </summary>
        NUMBER_50000 = 50000

    }

}
