/*
 * StarkExpress API Docs
 *
 * An API for the StarkExpress platform.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = StarkExpress.SDK.Client.Client.OpenAPIDateConverter;

namespace StarkExpress.SDK.Client.Model
{
    /// <summary>
    /// Model containing information to mint an asset.
    /// </summary>
    [DataContract(Name = "MintDataModel")]
    public partial class MintDataModel : IEquatable<MintDataModel>, IValidatableObject
    {

        /// <summary>
        /// Gets or Sets DataAvailabilityMode
        /// </summary>
        [DataMember(Name = "dataAvailabilityMode", IsRequired = true, EmitDefaultValue = true)]
        public DataAvailabilityModes DataAvailabilityMode { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="MintDataModel" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected MintDataModel() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="MintDataModel" /> class.
        /// </summary>
        /// <param name="mintingBlob">The hexadecimal string representation of the data to be associated with the asset being minted. (required).</param>
        /// <param name="assetId">The unique identifier of the asset being minted. (required).</param>
        /// <param name="amount">The amount of the asset to be minted. (required).</param>
        /// <param name="dataAvailabilityMode">dataAvailabilityMode (required).</param>
        public MintDataModel(string mintingBlob = default(string), Guid assetId = default(Guid), string amount = default(string), DataAvailabilityModes dataAvailabilityMode = default(DataAvailabilityModes))
        {
            // to ensure "mintingBlob" is required (not null)
            if (mintingBlob == null)
            {
                throw new ArgumentNullException("mintingBlob is a required property for MintDataModel and cannot be null");
            }
            this.MintingBlob = mintingBlob;
            this.AssetId = assetId;
            // to ensure "amount" is required (not null)
            if (amount == null)
            {
                throw new ArgumentNullException("amount is a required property for MintDataModel and cannot be null");
            }
            this.Amount = amount;
            this.DataAvailabilityMode = dataAvailabilityMode;
        }

        /// <summary>
        /// The hexadecimal string representation of the data to be associated with the asset being minted.
        /// </summary>
        /// <value>The hexadecimal string representation of the data to be associated with the asset being minted.</value>
        [DataMember(Name = "mintingBlob", IsRequired = true, EmitDefaultValue = true)]
        public string MintingBlob { get; set; }

        /// <summary>
        /// The unique identifier of the asset being minted.
        /// </summary>
        /// <value>The unique identifier of the asset being minted.</value>
        [DataMember(Name = "assetId", IsRequired = true, EmitDefaultValue = true)]
        public Guid AssetId { get; set; }

        /// <summary>
        /// The amount of the asset to be minted.
        /// </summary>
        /// <value>The amount of the asset to be minted.</value>
        [DataMember(Name = "amount", IsRequired = true, EmitDefaultValue = true)]
        public string Amount { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class MintDataModel {\n");
            sb.Append("  MintingBlob: ").Append(MintingBlob).Append("\n");
            sb.Append("  AssetId: ").Append(AssetId).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  DataAvailabilityMode: ").Append(DataAvailabilityMode).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as MintDataModel);
        }

        /// <summary>
        /// Returns true if MintDataModel instances are equal
        /// </summary>
        /// <param name="input">Instance of MintDataModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(MintDataModel input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.MintingBlob == input.MintingBlob ||
                    (this.MintingBlob != null &&
                    this.MintingBlob.Equals(input.MintingBlob))
                ) && 
                (
                    this.AssetId == input.AssetId ||
                    (this.AssetId != null &&
                    this.AssetId.Equals(input.AssetId))
                ) && 
                (
                    this.Amount == input.Amount ||
                    (this.Amount != null &&
                    this.Amount.Equals(input.Amount))
                ) && 
                (
                    this.DataAvailabilityMode == input.DataAvailabilityMode ||
                    this.DataAvailabilityMode.Equals(input.DataAvailabilityMode)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.MintingBlob != null)
                {
                    hashCode = (hashCode * 59) + this.MintingBlob.GetHashCode();
                }
                if (this.AssetId != null)
                {
                    hashCode = (hashCode * 59) + this.AssetId.GetHashCode();
                }
                if (this.Amount != null)
                {
                    hashCode = (hashCode * 59) + this.Amount.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.DataAvailabilityMode.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            // MintingBlob (string) minLength
            if (this.MintingBlob != null && this.MintingBlob.Length < 1)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for MintingBlob, length must be greater than 1.", new [] { "MintingBlob" });
            }

            yield break;
        }
    }

}
