/*
 * StarkExpress API Docs
 *
 * An API for the StarkExpress platform.
 *
 * The version of the OpenAPI document: 1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = StarkExpress.SDK.Client.Client.OpenAPIDateConverter;

namespace StarkExpress.SDK.Client.Model
{
    /// <summary>
    /// Defines StarkExOperation
    /// </summary>
    [JsonConverter(typeof(StringEnumConverter))]
    public enum StarkExOperation
    {
        /// <summary>
        /// Enum Deposit for value: Deposit
        /// </summary>
        [EnumMember(Value = "Deposit")]
        Deposit = 1,

        /// <summary>
        /// Enum Withdrawal for value: Withdrawal
        /// </summary>
        [EnumMember(Value = "Withdrawal")]
        Withdrawal = 2,

        /// <summary>
        /// Enum Mint for value: Mint
        /// </summary>
        [EnumMember(Value = "Mint")]
        Mint = 3,

        /// <summary>
        /// Enum MultiTransaction for value: MultiTransaction
        /// </summary>
        [EnumMember(Value = "MultiTransaction")]
        MultiTransaction = 4,

        /// <summary>
        /// Enum Transfer for value: Transfer
        /// </summary>
        [EnumMember(Value = "Transfer")]
        Transfer = 5,

        /// <summary>
        /// Enum FullWithdrawal for value: FullWithdrawal
        /// </summary>
        [EnumMember(Value = "FullWithdrawal")]
        FullWithdrawal = 6,

        /// <summary>
        /// Enum FalseFullWithdrawal for value: FalseFullWithdrawal
        /// </summary>
        [EnumMember(Value = "FalseFullWithdrawal")]
        FalseFullWithdrawal = 7,

        /// <summary>
        /// Enum Settlement for value: Settlement
        /// </summary>
        [EnumMember(Value = "Settlement")]
        Settlement = 8

    }

}
