/*
 * StarkExpress API Docs
 *
 * An API for the StarkExpress platform.
 *
 * The version of the OpenAPI document: v1
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = StarkExpress.SDK.Client.Client.OpenAPIDateConverter;

namespace StarkExpress.SDK.Client.Model
{
    /// <summary>
    /// Request model to submit an orderbook order.
    /// </summary>
    [DataContract(Name = "SubmitOrderModel")]
    public partial class SubmitOrderModel : IEquatable<SubmitOrderModel>, IValidatableObject
    {

        /// <summary>
        /// Gets or Sets Side
        /// </summary>
        [DataMember(Name = "side", IsRequired = true, EmitDefaultValue = true)]
        public OrderSide Side { get; set; }

        /// <summary>
        /// Gets or Sets SellDataAvailabilityMode
        /// </summary>
        [DataMember(Name = "sellDataAvailabilityMode", IsRequired = true, EmitDefaultValue = true)]
        public DataAvailabilityModes SellDataAvailabilityMode { get; set; }

        /// <summary>
        /// Gets or Sets BuyDataAvailabilityMode
        /// </summary>
        [DataMember(Name = "buyDataAvailabilityMode", IsRequired = true, EmitDefaultValue = true)]
        public DataAvailabilityModes BuyDataAvailabilityMode { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="SubmitOrderModel" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SubmitOrderModel() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SubmitOrderModel" /> class.
        /// </summary>
        /// <param name="orderbookId">The ID of the orderbook. (required).</param>
        /// <param name="userId">The unique identifier of the user submitting the order. (required).</param>
        /// <param name="side">side (required).</param>
        /// <param name="price">The order price. (required).</param>
        /// <param name="amount">The order amount. (required).</param>
        /// <param name="sellDataAvailabilityMode">sellDataAvailabilityMode (required).</param>
        /// <param name="buyDataAvailabilityMode">buyDataAvailabilityMode (required).</param>
        /// <param name="expirationTimestamp">The timestamp at which this order becomes invalid, in seconds since the Unix epoch. (required).</param>
        /// <param name="nonce">The unique nonce for the order. (required).</param>
        /// <param name="signature">signature (required).</param>
        public SubmitOrderModel(Guid orderbookId = default(Guid), Guid userId = default(Guid), OrderSide side = default(OrderSide), double price = default(double), string amount = default(string), DataAvailabilityModes sellDataAvailabilityMode = default(DataAvailabilityModes), DataAvailabilityModes buyDataAvailabilityMode = default(DataAvailabilityModes), long expirationTimestamp = default(long), int nonce = default(int), SignatureModel signature = default(SignatureModel))
        {
            this.OrderbookId = orderbookId;
            this.UserId = userId;
            this.Side = side;
            this.Price = price;
            // to ensure "amount" is required (not null)
            if (amount == null)
            {
                throw new ArgumentNullException("amount is a required property for SubmitOrderModel and cannot be null");
            }
            this.Amount = amount;
            this.SellDataAvailabilityMode = sellDataAvailabilityMode;
            this.BuyDataAvailabilityMode = buyDataAvailabilityMode;
            this.ExpirationTimestamp = expirationTimestamp;
            this.Nonce = nonce;
            // to ensure "signature" is required (not null)
            if (signature == null)
            {
                throw new ArgumentNullException("signature is a required property for SubmitOrderModel and cannot be null");
            }
            this.Signature = signature;
        }

        /// <summary>
        /// The ID of the orderbook.
        /// </summary>
        /// <value>The ID of the orderbook.</value>
        [DataMember(Name = "orderbookId", IsRequired = true, EmitDefaultValue = true)]
        public Guid OrderbookId { get; set; }

        /// <summary>
        /// The unique identifier of the user submitting the order.
        /// </summary>
        /// <value>The unique identifier of the user submitting the order.</value>
        [DataMember(Name = "userId", IsRequired = true, EmitDefaultValue = true)]
        public Guid UserId { get; set; }

        /// <summary>
        /// The order price.
        /// </summary>
        /// <value>The order price.</value>
        [DataMember(Name = "price", IsRequired = true, EmitDefaultValue = true)]
        public double Price { get; set; }

        /// <summary>
        /// The order amount.
        /// </summary>
        /// <value>The order amount.</value>
        [DataMember(Name = "amount", IsRequired = true, EmitDefaultValue = true)]
        public string Amount { get; set; }

        /// <summary>
        /// The timestamp at which this order becomes invalid, in seconds since the Unix epoch.
        /// </summary>
        /// <value>The timestamp at which this order becomes invalid, in seconds since the Unix epoch.</value>
        [DataMember(Name = "expirationTimestamp", IsRequired = true, EmitDefaultValue = true)]
        public long ExpirationTimestamp { get; set; }

        /// <summary>
        /// The unique nonce for the order.
        /// </summary>
        /// <value>The unique nonce for the order.</value>
        [DataMember(Name = "nonce", IsRequired = true, EmitDefaultValue = true)]
        public int Nonce { get; set; }

        /// <summary>
        /// Gets or Sets Signature
        /// </summary>
        [DataMember(Name = "signature", IsRequired = true, EmitDefaultValue = true)]
        public SignatureModel Signature { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class SubmitOrderModel {\n");
            sb.Append("  OrderbookId: ").Append(OrderbookId).Append("\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            sb.Append("  Side: ").Append(Side).Append("\n");
            sb.Append("  Price: ").Append(Price).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  SellDataAvailabilityMode: ").Append(SellDataAvailabilityMode).Append("\n");
            sb.Append("  BuyDataAvailabilityMode: ").Append(BuyDataAvailabilityMode).Append("\n");
            sb.Append("  ExpirationTimestamp: ").Append(ExpirationTimestamp).Append("\n");
            sb.Append("  Nonce: ").Append(Nonce).Append("\n");
            sb.Append("  Signature: ").Append(Signature).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SubmitOrderModel);
        }

        /// <summary>
        /// Returns true if SubmitOrderModel instances are equal
        /// </summary>
        /// <param name="input">Instance of SubmitOrderModel to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SubmitOrderModel input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.OrderbookId == input.OrderbookId ||
                    (this.OrderbookId != null &&
                    this.OrderbookId.Equals(input.OrderbookId))
                ) && 
                (
                    this.UserId == input.UserId ||
                    (this.UserId != null &&
                    this.UserId.Equals(input.UserId))
                ) && 
                (
                    this.Side == input.Side ||
                    this.Side.Equals(input.Side)
                ) && 
                (
                    this.Price == input.Price ||
                    this.Price.Equals(input.Price)
                ) && 
                (
                    this.Amount == input.Amount ||
                    (this.Amount != null &&
                    this.Amount.Equals(input.Amount))
                ) && 
                (
                    this.SellDataAvailabilityMode == input.SellDataAvailabilityMode ||
                    this.SellDataAvailabilityMode.Equals(input.SellDataAvailabilityMode)
                ) && 
                (
                    this.BuyDataAvailabilityMode == input.BuyDataAvailabilityMode ||
                    this.BuyDataAvailabilityMode.Equals(input.BuyDataAvailabilityMode)
                ) && 
                (
                    this.ExpirationTimestamp == input.ExpirationTimestamp ||
                    this.ExpirationTimestamp.Equals(input.ExpirationTimestamp)
                ) && 
                (
                    this.Nonce == input.Nonce ||
                    this.Nonce.Equals(input.Nonce)
                ) && 
                (
                    this.Signature == input.Signature ||
                    (this.Signature != null &&
                    this.Signature.Equals(input.Signature))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.OrderbookId != null)
                {
                    hashCode = (hashCode * 59) + this.OrderbookId.GetHashCode();
                }
                if (this.UserId != null)
                {
                    hashCode = (hashCode * 59) + this.UserId.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.Side.GetHashCode();
                hashCode = (hashCode * 59) + this.Price.GetHashCode();
                if (this.Amount != null)
                {
                    hashCode = (hashCode * 59) + this.Amount.GetHashCode();
                }
                hashCode = (hashCode * 59) + this.SellDataAvailabilityMode.GetHashCode();
                hashCode = (hashCode * 59) + this.BuyDataAvailabilityMode.GetHashCode();
                hashCode = (hashCode * 59) + this.ExpirationTimestamp.GetHashCode();
                hashCode = (hashCode * 59) + this.Nonce.GetHashCode();
                if (this.Signature != null)
                {
                    hashCode = (hashCode * 59) + this.Signature.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            // Nonce (int) maximum
            if (this.Nonce > (int)2147483647)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Nonce, must be a value less than or equal to 2147483647.", new [] { "Nonce" });
            }

            // Nonce (int) minimum
            if (this.Nonce < (int)0)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Nonce, must be a value greater than or equal to 0.", new [] { "Nonce" });
            }

            yield break;
        }
    }

}
