openapi: 3.0.1
info:
  description: An API for the StarkExpress platform.
  license:
    name: License
    url: https://starkexpress.io/license
  termsOfService: https://starkexpress.io/terms
  title: StarkExpress API Docs
  version: "1.0"
  x-logo:
    url: https://starkexpress.io/_next/static/media/starkexpress-logo.c94e6c9d.svg
    altText: StarkExpress logo
servers:
- description: Testnet server (uses test data).
  url: https://testnet-api.starkexpress.io
- description: Mainnet server (uses live data).
  url: https://api.starkexpress.io
tags:
- description: Operations related with the user management.
  name: User
- description: Operations related with the management of assets in the tenant system.
  name: Asset
- description: "Operations related with the minting of ERC-20, ERC-721 and ERC-1155\
    \ assets."
  name: Mint
- description: Operations related with the transfer of assets.
  name: Transfer
- description: Operations related with the transactions submitted by the system.
  name: Transaction
- description: Operations related with the withdrawal of assets.
  name: Withdraw
- description: Operations related with the vault management.
  name: Vault
- description: Operations related with the configuration of the fee model in the tenant
    system.
  name: Fee
- description: Operations related with the orderbook management.
  name: Orderbook
- description: Operations related with the order management.
  name: Order
paths:
  /api/v1/fees:
    post:
      description: This endpoint allows to configure the fee model for a specific
        operation.
      operationId: ConfigureFeeModel
      summary: Configure Fee Model
      tags:
      - Fee
  /api/v1/fees/{feeId}:
    get:
      description: This endpoint fetches a configured operation fee by ID.
      operationId: GetFeeModel
      summary: Get Fee Model
      tags:
      - Fee
  /api/v1/mint:
    post:
      description: This endpoint allows for the minting of fungible and non-fungible
        assets.
      operationId: MintAssets
      security:
      - oauth2:
        - mint:assets
      summary: Mint Assets
      tags:
      - Mint
  /api/v1/orders/details:
    post:
      description: This endpoint allows for fetching details of an order to be signed.
      operationId: OrderDetails
      summary: Get Order Details (Not Implemented)
      tags:
      - Order
  /api/v1/orders:
    post:
      description: This endpoint submits an order to the matching engine.
      operationId: SubmitOrder
      summary: Submit Order (Not Implemented)
      tags:
      - Order
  /api/v1/orders/{orderId}:
    delete:
      description: This endpoint cancels an active order.
      operationId: CancelOrder
      summary: Cancel Order (Not Implemented)
      tags:
      - Order
  /api/v1/orderbooks:
    post:
      description: This endpoint creates an orderbook.
      operationId: CreateOrderbook
      summary: Create Orderbook (Not Implemented)
      tags:
      - Orderbook
  /api/v1/orderbooks/{orderbookId}:
    get:
      description: This endpoint fetches orderbook metadata by ID.
      operationId: GetOrderbook
      summary: Get Orderbook (Not Implemented)
      tags:
      - Orderbook
  /api/v1/orderbooks/{orderbookId}/l1:
    get:
      description: This endpoint fetches orderbook level 1 data by ID.
      operationId: GetOrderbookLevel1Data
      summary: Get Orderbook L1 Data (Not Implemented)
      tags:
      - Orderbook
  /api/v1/orderbooks/{orderbookId}/l2:
    get:
      description: This endpoint fetches orderbook level 2 data by ID.
      operationId: GetOrderbookLevel2Data
      summary: Get Orderbook L2 Data (Not Implemented)
      tags:
      - Orderbook
  /api/v1/settlements:
    post:
      description: This endpoint submits an order settlement.
      operationId: SubmitSettlement
      summary: Submit Settlement (Not Implemented)
      tags:
      - Settlement
  /api/v1/assets:
    get:
      description: "This endpoint fetches all assets enabled in the tenant system,\
        \ with support for filters and pagination."
      operationId: GetAllAssets
      security:
      - oauth2:
        - read:tenant_assets
      summary: Get All Assets
      tags:
      - Asset
    post:
      description: This endpoint allows to enable an asset in the tenant system.
      operationId: EnableAsset
      security:
      - oauth2:
        - write:tenant_assets
      summary: Enable Asset
      tags:
      - Asset
  /api/v1/assets/{assetId}:
    get:
      description: This endpoint fetches a specific enabled asset by ID.
      operationId: GetAsset
      security:
      - oauth2:
        - read:tenant_assets
      summary: Get Asset
      tags:
      - Asset
  /api/v1/transactions:
    get:
      description: "This endpoint fetches all transactions submitted by the system,\
        \ with support for filters and pagination."
      operationId: GetAllTransactions
      security:
      - oauth2:
        - read:transactions
      summary: Get All Transactions
      tags:
      - Transaction
  /api/v1/transactions/{transactionId}:
    get:
      description: This endpoint fetches a specific transaction by ID.
      operationId: GetTransaction
      security:
      - oauth2:
        - read:transactions
      summary: Get Transaction
      tags:
      - Transaction
  /api/v1/transfers:
    post:
      description: This endpoint allows for transferring assets between users.
      operationId: Transfer
      security:
      - oauth2:
        - write:transfers
      summary: Transfer Asset
      tags:
      - Transfer
  /api/v1/transfers/details:
    post:
      description: This endpoint allows for fetching details of a transfer to be signed
        (allocates a vault for the receiver)
      operationId: TransferDetails
      security:
      - oauth2:
        - write:transfers
      summary: Get Transfer Details
      tags:
      - Transfer
  /api/v1/users:
    get:
      description: This endpoint fetches all users.
      operationId: GetAllUsers
      security:
      - oauth2:
        - read:users
      summary: Get All Users
      tags:
      - User
    post:
      description: This endpoint registers a user.
      operationId: RegisterUser
      security:
      - oauth2:
        - write:users
      summary: Register new User
      tags:
      - User
  /api/v1/users/register-details:
    get:
      description: This endpoint return the typed data to be signed with EIP712 that
        is used on user registration.
      operationId: EIP712Details
      security:
      - oauth2:
        - read:users
      summary: Get EIP712 data to be signed
      tags:
      - User
  /api/v1/users/{userId}:
    get:
      description: This endpoint fetches a specific user by ID.
      operationId: GetUser
      security:
      - oauth2:
        - read:users
      summary: Get User
      tags:
      - User
  /api/v1/vaults/deposit-details:
    post:
      description: "This endpoint returns the deposit details for a given user, asset,\
        \ and data availability mode."
      operationId: DepositDetails
      security:
      - oauth2:
        - read:vaults
        - write:vaults
      summary: Returns the deposit details for a given asset.
      tags:
      - Deposit
  /api/v1/vaults:
    get:
      description: "This endpoint fetches all vaults in the system, with support for\
        \ filters and pagination."
      operationId: GetAllVaults
      security:
      - oauth2:
        - read:vaults
      summary: Get All Vaults
      tags:
      - Vault
  /api/v1/vaults/{vaultId}:
    get:
      description: This endpoint fetches a vault identified by its unique id.
      operationId: GetVault
      security:
      - oauth2:
        - read:vaults
      summary: Get a single Vault
      tags:
      - Vault
  /api/v1/vaults/withdraw:
    post:
      description: This endpoint allows for withdrawing assets from StarkExpress.
      operationId: Withdraw
      security:
      - oauth2:
        - write:vaults
      summary: Withdraw Asset
      tags:
      - Withdraw
components:
  securitySchemes:
    oauth2:
      flows:
        clientCredentials:
          scopes:
            write:users: Access user write operations.
            read:users: Access user read operations.
            read:tenant_assets: Access tenant asset read operations.
            write:tenant_assets: Access tenant asset write operations.
            mint:assets: Access mint operations.
            read:vaults: Access vault read operations.
            write:transfers: Access transfer write operations.
            read:transfers: Access transfer read operations.
          tokenUrl: https://starkexpress-testnet.eu.auth0.com/oauth/token
      type: oauth2

