openapi: 3.0.1
info:
  description: An API for the Arc platform.
  license:
    name: License
    url: https://onarc.io/license
  termsOfService: https://onarc.io/terms
  title: Arc API Docs
  version: "1.0"
  x-logo:
    url: https://www.onarc.io/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Flogo_arc.9cf6e0e6.svg&w=828&q=75
    altText: Arc logo
servers:
- description: Testnet server (uses test data).
  url: https://testnet-api.onarc.io
- description: Mainnet server (uses live data).
  url: https://api.onarc.io
tags:
- description: Operations related with the user management.
  name: User
- description: Operations related with the management of assets in the tenant system.
  name: Asset
- description: "Operations related with the minting of ERC-20, ERC-721 and ERC-1155\
    \ assets."
  name: Mint
- description: Operations related with the transfer of assets.
  name: Transfer
- description: Operations related with the transactions submitted by the system.
  name: Transaction
- description: Operations related with the withdrawal of assets.
  name: Withdraw
- description: Operations related with the vault management.
  name: Vault
- description: Operations related with the configuration of the fee model in the tenant
    system.
  name: Fee
- description: Operations related with the orderbook management.
  name: Orderbook
- description: Operations related with the order management.
  name: Order
- description: Operations related with the settlement of assets.
  name: Settlement
paths:
  /api/v1/fees:
    post:
      description: This endpoint allows to configure the fee model for a specific
        operation.
      operationId: ConfigureFeeModel
      summary: Configure Fee Model
      tags:
      - Fee
  /api/v1/fees/{feeId}:
    get:
      description: This endpoint fetches a configured operation fee by ID.
      operationId: GetFeeModel
      summary: Get Fee Model
      tags:
      - Fee
  /api/v1/marketplace/sell-details:
    post:
      description: This endpoint returns the details for a sell offer in the public
        marketplace.
      operationId: SellOfferDetails
      security:
      - apikey:
        - write:sell-offers
      summary: Get sell offer details
      tags:
      - Marketplace
  /api/v1/marketplace/sell:
    post:
      description: This endpoint registers a sell offer in the public marketplace.
      operationId: RegisterSellOffer
      security:
      - apikey:
        - write:sell-offers
      summary: Register sell offer
      tags:
      - Marketplace
  /api/v1/marketplace/sell/{offerId}:
    delete:
      description: This endpoint deletes a sell offer in the public marketplace.
      operationId: DeleteSellOffer
      security:
      - apikey:
        - write:sell-offers
      summary: Delete sell offer
      tags:
      - Marketplace
  /api/v1/marketplace/sell-offers:
    get:
      description: This endpoint returns a paginated list of sell offer in the public
        marketplace.
      operationId: ListSellOffers
      security:
      - apikey:
        - read:sell-offers
      summary: List sell offers
      tags:
      - Marketplace
  /api/v1/marketplace/buy-details:
    post:
      description: This endpoint returns the details for a buy order in the public
        marketplace.
      operationId: BuyOrderDetails
      security:
      - apikey:
        - write:buy-orders
      summary: Get buy order details
      tags:
      - Marketplace
  /api/v1/marketplace/buy:
    post:
      description: This endpoint buys a product listed in the public marketplace.
      operationId: RegisterBuyOrder
      security:
      - apikey:
        - write:buy-orders
      summary: Register buy order
      tags:
      - Marketplace
  /api/v1/marketplace/buy-orders:
    get:
      description: This endpoint returns a paginated list of buy orders in the public
        marketplace.
      operationId: ListBuyOrders
      security:
      - apikey:
        - read:buy-orders
      summary: List buy orders
      tags:
      - Marketplace
  /api/v1/mint:
    post:
      description: This endpoint allows for the minting of fungible and non-fungible
        assets.
      operationId: MintAssets
      security:
      - apikey:
        - mint:assets
      summary: Mint Assets
      tags:
      - Mint
  /api/v1/orders/details:
    post:
      description: This endpoint allows for fetching details of an order to be signed.
      operationId: OrderDetails
      summary: Get Order Details (Not Implemented)
      tags:
      - Order
  /api/v1/orders:
    post:
      description: This endpoint submits an order to the matching engine.
      operationId: SubmitOrder
      summary: Submit Order (Not Implemented)
      tags:
      - Order
  /api/v1/orders/{orderId}:
    delete:
      description: This endpoint cancels an active order.
      operationId: CancelOrder
      summary: Cancel Order (Not Implemented)
      tags:
      - Order
  /api/v1/orderbooks:
    post:
      description: This endpoint creates an orderbook.
      operationId: CreateOrderbook
      summary: Create Orderbook (Not Implemented)
      tags:
      - Orderbook
  /api/v1/orderbooks/{orderbookId}:
    get:
      description: This endpoint fetches orderbook metadata by ID.
      operationId: GetOrderbook
      summary: Get Orderbook (Not Implemented)
      tags:
      - Orderbook
  /api/v1/orderbooks/{orderbookId}/l1:
    get:
      description: This endpoint fetches orderbook level 1 data by ID.
      operationId: GetOrderbookLevel1Data
      summary: Get Orderbook L1 Data (Not Implemented)
      tags:
      - Orderbook
  /api/v1/orderbooks/{orderbookId}/l2:
    get:
      description: This endpoint fetches orderbook level 2 data by ID.
      operationId: GetOrderbookLevel2Data
      summary: Get Orderbook L2 Data (Not Implemented)
      tags:
      - Orderbook
  /api/v1/settlements:
    post:
      description: This endpoint submits an order settlement.
      operationId: SubmitSettlement
      security:
      - apikey:
        - write:settlements
      summary: Submit Settlement
      tags:
      - Settlement
  /api/v1/assets:
    get:
      description: "This endpoint fetches all assets enabled in the tenant system,\
        \ with support for filters and pagination."
      operationId: GetAllAssets
      security:
      - apikey:
        - read:tenant_assets
      summary: Get All Assets
      tags:
      - Asset
    post:
      description: This endpoint allows to enable an asset in the tenant system.
      operationId: EnableAsset
      security:
      - apikey:
        - write:tenant_assets
      summary: Enable Asset
      tags:
      - Asset
  /api/v1/assets/disable:
    post:
      description: This endpoint allows to disable an asset in the tenant system.
      operationId: DisableAsset
      security:
      - apikey:
        - write:tenant_assets
      summary: Disable Asset
      tags:
      - Asset
  /api/v1/assets/{assetId}:
    get:
      description: This endpoint fetches a specific enabled asset by ID.
      operationId: GetAsset
      security:
      - apikey:
        - read:tenant_assets
      summary: Get Asset
      tags:
      - Asset
  /api/v1/assets/deploy:
    post:
      description: This endpoint allows for deploying an asset and enable it in the
        tenant system.
      operationId: Deploy Asset
      security:
      - apikey:
        - write:tenant_assets
        - write:smart-contracts
      summary: Deploy Asset
      tags:
      - Asset
  /api/v1/assets/estimate-deploy:
    get:
      description: This endpoint allows for deploying an asset and enable it in the
        tenant system.
      operationId: Estimate Asset Deploy Cost
      security:
      - apikey:
        - write:tenant_assets
        - write:smart-contracts
      summary: Estimate cost of the deployment for a new Asset
      tags:
      - Asset
  /api/v1/transactions:
    get:
      description: "This endpoint fetches all transactions submitted by the system,\
        \ with support for filters and pagination."
      operationId: GetAllTransactions
      security:
      - apikey:
        - read:transactions
      summary: Get All Transactions
      tags:
      - Transaction
  /api/v1/transactions/{transactionId}:
    get:
      description: This endpoint fetches a specific transaction by ID.
      operationId: GetTransaction
      security:
      - apikey:
        - read:transactions
      summary: Get Transaction
      tags:
      - Transaction
  /api/v1/transfers:
    post:
      description: This endpoint allows for transferring assets between users.
      operationId: Transfer
      security:
      - apikey:
        - write:transfers
      summary: Transfer Asset
      tags:
      - Transfer
  /api/v1/transfers/details:
    post:
      description: This endpoint allows for fetching details of a transfer to be signed
        (allocates a vault for the receiver)
      operationId: TransferDetails
      security:
      - apikey:
        - write:transfers
      summary: Get Transfer Details
      tags:
      - Transfer
  /api/v1/users:
    get:
      description: This endpoint fetches all users.
      operationId: GetAllUsers
      security:
      - apikey:
        - read:users
      summary: Get All Users
      tags:
      - User
    post:
      description: This endpoint registers a user.
      operationId: RegisterUser
      security:
      - apikey:
        - write:users
      summary: Register new User
      tags:
      - User
  /api/v1/users/register-details:
    get:
      description: This endpoint return the typed data to be signed with EIP712 that
        is used on user registration.
      operationId: EIP712Details
      security:
      - apikey:
        - read:users
      summary: Get EIP712 data to be signed
      tags:
      - User
  /api/v1/users/{userId}:
    get:
      description: This endpoint fetches a specific user by ID.
      operationId: GetUser
      security:
      - apikey:
        - read:users
      summary: Get User
      tags:
      - User
  /api/v1/vaults/deposit-details:
    post:
      description: "This endpoint returns the deposit details for a given user, asset,\
        \ and data availability mode."
      operationId: DepositDetails
      security:
      - apikey:
        - read:vaults
        - write:vaults
      summary: Returns the deposit details for a given asset.
      tags:
      - Deposit
  /api/v1/vaults:
    get:
      description: "This endpoint fetches all vaults in the system, with support for\
        \ filters and pagination."
      operationId: GetAllVaults
      security:
      - apikey:
        - read:vaults
      summary: Get All Vaults
      tags:
      - Vault
    post:
      description: "This endpoint allocates a new vault for a given asset, if there\
        \ isn't one already allocated."
      operationId: AllocateVault
      security:
      - apikey:
        - write:vaults
      summary: Allocate vault
      tags:
      - Vault
  /api/v1/vaults/{vaultId}:
    get:
      description: This endpoint fetches a vault identified by its unique id.
      operationId: GetVault
      security:
      - apikey:
        - read:vaults
      summary: Get a single Vault
      tags:
      - Vault
  /api/v1/vaults/withdraw:
    post:
      description: This endpoint allows for withdrawing assets from StarkExpress.
      operationId: Withdraw
      security:
      - apikey:
        - write:vaults
      summary: Withdraw Asset
      tags:
      - Withdraw
components:
  securitySchemes:
    apikey:
      description: API Key Authentication
      in: header
      name: x-api-key
      type: apiKey

