name: Main branch workflow

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    name: Build and Publish SDKs
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
    env:
      dotnet-version: '6.0'

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET Core SDK ${{ env.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.dotnet-version }}

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm install

      - name: Publish using semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NUGET_TOKEN: ${{ secrets.NUGET_API_KEY }}
        run: npx semantic-release