name: Tags workflow

on:
  push:
    tags:
      - 'v[0-9].[0-9].[0-9]'

jobs:
  build:
    name: Build and Publish SDKs
    runs-on: ubuntu-latest
    env:
      dotnet-version: '6.0'

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup .NET Core SDK ${{ env.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.dotnet-version }}

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Tag version
        id: sdk-version
        uses: paulhatch/semantic-version@v4.0.2
        with:
          format: "${major}.${minor}.${patch}"
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"

      - name: Package
        run: dotnet pack --configuration Release  -p:Version=${{ steps.sdk-version.outputs.version }}

      # Publish to github
      - name: Add nuget sources
        run: dotnet nuget add source --username USERNAME --password ${{ secrets.API_TOKEN_GITHUB }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/threesigmaxyz/index.json"

      - name: Publish SDK to github
        run: dotnet nuget push "src/StarkExpress.SDK.Client/bin/Release/*.nupkg" --api-key ${{ secrets.API_TOKEN_GITHUB }} --source "github"

      # Publish to nuget.org
      - name: Publish  to nuget.org
        run: dotnet nuget push "src/StarkExpress.SDK.Client/bin/Release/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source "nuget.org"
